title: Article No.1 : A milestone for a project that will never come fully to fruition
author: John Doe
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site? The best site there has ever been and the best site that ever will be. There's all kind of content on here,
  and approximately 67% is amazing. Is there any sort of consistent theme to it? Nah, not really. But that makes it open
  to include more people's interest and be even more amazing. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  johndoe-js # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
